var core = require('./core');
var Sandbox = require('./facade');
// var socketModule = require('./modules/socketController');
var dashboard = require('./modules/subscribeButtons');
var REST = require('./modules/REST')
var notifications = require('./modules/notifications')
var stats = require('./modules/stats')
var settings = require('./modules/settings')
var loading = require('./modules/loading')
//var serviceWorker = require('./modules/webPushButton')